# Generated by Django 5.0.3 on 2024-03-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
