# Generated by Django 5.0.3 on 2024-03-13 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='items',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clientitems'),
        ),
    ]
