# Generated by Django 5.0.3 on 2024-03-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientinfo_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinfo',
            name='items',
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='clients.clientitems'),
        ),
    ]
