# Generated by Django 5.0.3 on 2024-03-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_clientinfo_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
