# Generated by Django 5.0.3 on 2024-03-29 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_clientinfo_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='client_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clientaddress'),
        ),
    ]
