# Generated by Django 5.0.3 on 2024-03-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_clientinfo_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
