# Generated by Django 5.0.3 on 2024-03-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_clientinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='client_email',
            field=models.EmailField(max_length=254),
        ),
    ]
