# Generated by Django 5.0.3 on 2024-04-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_alter_clientinfo_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], max_length=200),
        ),
    ]
