# Generated by Django 5.0.3 on 2024-05-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_active_alter_tasks_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='is_active',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='completed',
            name='is_completed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
