# Generated by Django 5.0.3 on 2024-05-07 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='active',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.active'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='completed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.completed'),
        ),
    ]
