# Generated by Django 5.0.3 on 2024-05-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasks_active_alter_tasks_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
