# Generated by Django 5.0.3 on 2024-05-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_tasks_active_remove_tasks_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='active',
            field=models.ManyToManyField(blank=True, to='tasks.active'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='completed',
            field=models.ManyToManyField(blank=True, to='tasks.completed'),
        ),
    ]
